version: "3.0"

services:
    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.0
        ports:
            - 5601:5601
        container_name: kibana_workshop
        depends_on: 
            - elasticsearch
        environment: 
            - SERVER_HOST=0.0.0.0
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        container_name: elasticsearch_workshop
        volumes:
            - ./data:/data
        environment: 
            - discovery.type=single-node
            - path.data=/data
